language: php

php:
- nightly
- 7.3
- 7.2
- 7.1
- 7.0
- 5.6
- 5.5

matrix:
  fast_finish: true
  allow_failures:
  - php: nightly
  - php: 7.3


before_install:
# Disabling Xdebug - Debugger and Profiler Tool for PHP
- |
  php -r "print_r(get_loaded_extensions(TRUE));"
  if [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
    cat ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
    install --directory ~/.phpenv/versions/$(phpenv version-name)/etc/on-demand
    mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ~/.phpenv/versions/$(phpenv version-name)/etc/on-demand
    php -r "print_r(get_loaded_extensions(TRUE));"
  fi


script:
# - php hello-time.php
- |
  /usr/bin/time --format '%M %S %U %I %O' php << EOT
  <?php
  echo 'hello'.PHP_EOL;
  EOT
