language: php

php:
- nightly
- 7.2
- 7.1
- 7.0
- 5.6
- 5.5

matrix:
  fast_finish: true
  allow_failures:
  - php: nightly

script:
# - php hello-time.php
- |
  /usr/bin/time --format '%M %S %U %I %O' php << EOT
  <?php
  echo 'hello'.PHP_EOL;
  EOT
